application: snipbin
version: 5
runtime: python
api_version: 1

handlers:
- url: /
  script: py/handlers/main.py
  
- url: /my
  script: py/handlers/main.py
  login: required
  
- url: /view
  script: py/handlers/view.py
  
- url: /inc
  script: py/handlers/view.py
  
- url: /helper
  script: py/handlers/view.py
  
- url: /test
  script: test/test.py
  login: admin
  
- url: /admin/.*
  script: py/handlers/admin.py
  login: admin
  
- url: /api/.*
  script: py/handlers/api.py
  
- url: /stylesheets
  static_dir: stylesheets
  
- url: /js
  static_dir: js
  
- url: /(.*\.(gif|png|jpg|ico|txt))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|ico|txt))  

- url: /(about|legal|extension|extwelcome|credits)
  script: py/handlers/plainhtml.py
  
- url: /extlogin
  script: py/handlers/plainhtml.py
  login: required
  
- url: /logout
  script: py/handlers/logout.py
  login: required